script/upload: add a --finalize option
When the build and upload process is automated, the only thing left for
the maintainer to do will be to download the assets, sign the hashes,
and upload the signed manifest.  To make this easy and mostly automated,
add an option to the upload script, --finalize, that downloads assets,
optionally allows the maintainer to inspect them, and then uploads the
signed manifest to the GitHub release.

diff --git a/script/upload b/script/upload
--- a/script/upload
+++ b/script/upload
@@ -123,13 +123,36 @@ create_release () {
     sed -e 's/{.*}//g'
 }
 
+# Update the draft release with a new body and print the upload URL for release assets to the
+# standard output.  A release with the given version must already exist.
+patch_release () {
+  local version="$1"
+  local bodyfile="$2"
+
+  # Find the URL of this release.
+  local url=$(curl https://api.github.com/repos/$REPO/releases | \
+    jq -r '.[] | select(.name == "'"$version"'") | .url')
+
+  [ -n "$url" ] || abort "No existing release found for version $version."
+  say "Found the existing release for this version."
+
+  # This can be large, so pass it in a file.
+  format_release_json "$version" "$bodyfile" >> "$WORKDIR/release-json"
+
+  curl -XPATCH -H'Content-Type: application/json' -d"@$WORKDIR/release-json" \
+    $url | \
+    jq -r '.upload_url' |
+    sed -e 's/{.*}//g'
+}
+
 # Find the release files for the given version.
 release_files () {
   local version="$1"
+  local assets="${2:-bin/releases}"
 
   [ -n "$version" ] || return 1
 
-  find bin/releases -name '*.tar.gz' -o -name '*386*.zip' -o \
+  find "$assets" -name '*.tar.gz' -o -name '*386*.zip' -o \
     -name '*amd64*.zip' -o -name '*.exe' -o -name 'sha256sums.asc' | \
     grep -E "$version|sha256sums.asc" | \
     grep -v "assets" | \
@@ -141,6 +164,7 @@ release_files () {
 finalize_body_message () {
   local version="$1"
   local changelog="$2"
+  local assets="$3"
 
   version=$(echo "$version" | sed -e 's/^v//')
 
@@ -161,7 +185,7 @@ Up to date packages are available on [PackageCloud](https://packagecloud.io/gith
 ## SHA-256 hashes:
 EOM
 
-  shasum -a256 $(release_files "$version") | \
+  shasum -a256 $(release_files "$version" "$assets") | \
     ruby -pe '$_.chomp!' \
     -e '$_.gsub!(/^([0-9a-f]+)\s+.*\/([^\/]+)$/, "**\\2**\n\\1\n\n")' | \
     ruby -0777 -pe '$_.gsub!(/\n+\z/, "\n")' >> "$WORKDIR/body-template"
@@ -197,8 +221,6 @@ upload_assets () {
     jq -r '.[] | select(.name == "'"$version"'") | .assets | .[] | .name' \
     > "$WORKDIR/existing-assets"
 
-  mkdir "$WORKDIR/downloads"
-
   for file in $(release_files "$version" | filter_files "$WORKDIR/existing-assets")
   do
     base=$(basename "$file")
@@ -229,7 +251,7 @@ download_assets () {
 
   cat "$WORKDIR/assets" | (while read base url
   do
-    say "\tDownloading %s for verification..." "$base"
+    say "\tDownloading %s..." "$base"
     (
       cd "$dir" &&
       curl -Lo "$base" -H"Accept: application/octet-stream" "$url"
@@ -266,6 +288,49 @@ extract_changelog () {
   echo "$WORKDIR/changelog"
 }
 
+# Perform the final steps to verify a release
+finalize () {
+  local version="$1"
+  local inspect="$2"
+  local downloads="$WORKDIR/finalize"
+
+  say "Finalizing the release process..."
+  say "Downloading assets..."
+
+  mkdir "$downloads"
+  download_assets "$version" "$downloads"
+
+  if [ -n "$inspect" ]
+  then
+    say "Dropping you to a shell to inspect the assets."
+    say "Type 'exit 0' to continue, or 'exit 1' to abort."
+
+    (cd "$downloads" && $SHELL)
+  fi
+
+  say "Signing asset manifest..."
+  (
+    cd "$downloads" && \
+    shasum -a256 -b * | grep -vE '(assets|sha256sums)' | \
+        gpg --digest-algo SHA256 --clearsign >sha256sums.asc
+  )
+
+  say "Formatting the final body of the GitHub release now..."
+
+  local changelog=$(extract_changelog "$version")
+  local bodyfile=$(finalize_body_message "$version" "$changelog" "$downloads")
+
+  say "Uploading final release body..."
+
+  local upload_url=$(patch_release "$version" "$bodyfile")
+
+  say "Uploading final versions of assets..."
+  cp "$downloads/sha256sums.asc" bin/releases
+  upload_assets "$version" "$upload_url"
+
+  # Verification occurs in caller below.
+}
+
 # Provide a helpful usage message and exit.
 usage () {
   local status="$1"
@@ -277,7 +342,7 @@ the changelog specified in the file CHANGELOG. Before running this script, the
 release assets should be built and ready for upload, including the signed
 sha256sums.asc file.
 
-This script requires ruby, curl, shasum, and jq.
+This script requires ruby, gpg, curl, shasum, and jq.
 EOM
   exit $status
 }
@@ -285,10 +350,15 @@ EOM
 # Check that this script has the prerequisites to continue.
 sanity_check () {
   local version="$1"
+  local finalize="$2"
 
   say "Checking that you've got some release artifacts..."
-  [ -n "$(release_files "$version")" ] || \
-    abort "I couldn't find any release files for $version."
+  if [ -n "$(release_files "$version")" ]
+  then
+    [ -z "$finalize" ] || abort "You'll need an empty bin/releases directory to continue."
+  else
+    [ -n "$finalize" ] || abort "I couldn't find any release files for $version."
+  fi
 
   if [ -n "$GITHUB_TOKEN" ]
   then
@@ -306,13 +376,21 @@ sanity_check () {
 
 # The main program.
 main () {
+  local inspect=""
+
   while [ -n "$1" ]
   do
     case "$1" in
       --help)
         usage 0;;
+      --inspect)
+        inspect=1
+        shift;;
       --skip-verify)
         SKIP_VERIFY=1
+        shift;;
+      --finalize)
+        FINALIZE=1
         shift;;
       --)
         shift
@@ -326,19 +404,24 @@ main () {
 
   [ -z "$version" ] && usage 1 >&2
 
-  sanity_check "$version"
+  sanity_check "$version" "$FINALIZE"
 
-  say "Formatting the body of the GitHub release now..."
+  if [ -n "$FINALIZE" ]
+  then
+    finalize "$version" "$inspect"
+  else
+    say "Formatting the body of the GitHub release now..."
 
-  local changelog=$(extract_changelog "$version")
-  local bodyfile=$(finalize_body_message "$version" "$changelog")
+    local changelog=$(extract_changelog "$version")
+    local bodyfile=$(finalize_body_message "$version" "$changelog")
 
-  say "Creating a GitHub release for %s..." "$version"
+    say "Creating a GitHub release for %s..." "$version"
 
-  local upload_url=$(create_release "$version" "$bodyfile")
+    local upload_url=$(create_release "$version" "$bodyfile")
 
-  say "Uploading assets to GitHub..."
-  upload_assets "$version" "$upload_url"
+    say "Uploading assets to GitHub..."
+    upload_assets "$version" "$upload_url"
+  fi
 
   if [ -z "$SKIP_VERIFY" ]
   then
